backend:
  name: github
  branch: main # Change this if your branch isn't `main`

media_folder: "images/uploads" # Folder where images will be stored
public_folder: "/images/uploads" # Public path for uploaded images

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
